name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
        # make depends on uv
      - name: Install dependencies
        run: |
          pip install uv
          make install
      - name: Install package
        run: pip install -e .
      - name: Run linter (flake8)
        run: flake8 gendiff tests
      - name: Run tests with coverage
        run: pytest --cov=gendiff --cov-report xml
      - name: Run linter and pytest
        run: |
          make check
      - name: Run test coverage
        run: |
          make test-coverage
      - name: Install CodeClimate test-reporter
        run: |
          curl -L https://github.com/codeclimate/test-reporter/releases/latest/download/codeclimate-test-reporter-linux-amd64 \
          -o ./cc-test-reporter
          chmod +x ./cc-test-reporter

      - name: Before build
        run: ./cc-test-reporter before-build

      - name: After build
        run: ./cc-test-reporter after-build --exit-code $?
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      - name: SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=hexlet-boilerplates_python-package
            -Dsonar.organization=hexlet-boilerplates
            -Dsonar.python.coverage.reportPaths=coverage.xml
